#!/bin/bash
# Exit on error
# If something goes wrong just stop.
# it allows the user to see issues at once rather than having
# scroll back and figure out what went wrong.
set -e

## Intended to run on top of the image generated by build_raspOVOS.sh

# Activate the virtual environment
source /home/$USER/.venvs/ovos/bin/activate

echo "Copying overlays..."
sudo cp -rv /mounted-github-repo/overlays/it/* /

echo "Setting up default wifi country..."
/usr/bin/raspi-config nonint do_wifi_country IT

echo "Installing Italian specific skills"
uv pip install --no-progress ovos-core[skills-it] -c $CONSTRAINTS

echo "Installing Italian Citrinet plugin..."
uv pip install --no-progress ovos-stt-plugin-citrinet -c $CONSTRAINTS

echo "Downloading Italian citrinet model..."
python -c "from huggingface_hub import hf_hub_download; repo_id='neongeckocom/stt_it_citrinet_512_gamma_0_25'; subfolder='onnx'; files=['model.onnx', 'tokenizer.spm', 'preprocessor.ts']; [print(f'Downloaded {file} to {hf_hub_download(repo_id=repo_id, filename=file, subfolder=subfolder)}') for file in files]"
# since script was run as root, we need to move downloaded files
mkdir -p /home/ovos/.cache/huggingface/hub/
mv /root/.cache/huggingface/hub/models--neongeckocom--stt_it_citrinet_512_gamma_0_25/ /home/ovos/.cache/huggingface/hub/models--neongeckocom--stt_it_citrinet_512_gamma_0_25/

echo "Installing Piper TTS..."
uv pip install --no-progress ovos-tts-plugin-piper -c $CONSTRAINTS

echo "Creating system level mycroft.conf..."
mkdir -p /etc/mycroft

echo "Ensuring permissions for $USER user..."
# Replace 1000:1000 with the correct UID:GID if needed
chown -R 1000:1000 /home/$USER

echo "Cleaning up apt packages..."
apt-get --purge autoremove -y && apt-get clean
