#!/usr/bin/env python3

import sdnotify
from ovos_dinkum_listener.__main__ import main

n = sdnotify.SystemdNotifier()


def notify_ready():
    n.notify('READY=1')
    print('Startup of Mycroft Voice service complete')


def notify_stopping():
    n.notify('STOPPING=1')
    print('Stopping the Mycroft Voice service')


main(ready_hook=notify_ready, stopping_hook=notify_stopping)
