#!/usr/bin/env python3

import sdnotify
from ovos_dinkum_listener.__main__ import main
from ovos_utils.log import LOG

n = sdnotify.SystemdNotifier()


def notify_started():
    n.notify('STARTED=1')
    LOG.info("OVOS Listener service started!")


def notify_ready():
    n.notify('READY=1')
    LOG.info('Startup of OVOS Listener service complete')


def notify_stopping():
    n.notify('STOPPING=1')
    LOG.info('Stopping the OVOS Listener service')


if __name__ == "__main__":
    try:
        main(started_hook=notify_started,
             ready_hook=notify_ready,
             stopping_hook=notify_stopping)
    except Exception as e:
        LOG.error(f"OVOS Listener Service encountered an error: {e}")
        n.notify(f'ERRNO=1')
        exit(1)
