#!/usr/bin/env python
import time

from ovos_bus_client.message import Message
from ovos_bus_client.util import get_mycroft_bus
from ovos_utils.ocp import PlayerState

bus = get_mycroft_bus()
bus.connected_event.wait()

bus.emit(Message("ovos.common_play.player.state",
                 {"state": PlayerState.PAUSED}))
time.sleep(1)
bus.close()
