name: build headless image

on:
  workflow_dispatch:

jobs:
  modify-rpi-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Add OVOS to Raspberry Pi OS Bookworm
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
          CONSTRAINTS: "https://github.com/OpenVoiceOS/ovos-releases/raw/refs/heads/main/constraints-alpha.txt"
        with:
          base-image-url: https://github.com/TigreGotico/raspOVOS/releases/download/raspOVOS-NO-OVOS-bookworm-arm64-lite-12053618536/raspOVOS-NO-OVOS-bookworm-arm64-lite.img.xz
          image-path: raspOVOS-bookworm-arm64-lite.img
          compress-with-xz: true
          shrink: true
          cache: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME,CONSTRAINTS
          script-path: build_raspOVOS.sh
      -
        name: Get Current Date
        id: current-date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      -
        name: Print outputs
        shell: bash
        run: |
          echo 'image-path: ${{ steps.create-image.outputs.image-path }}'
          echo 'image-size: ${{ steps.create-image.outputs.image-size }}'
          echo 'image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}'
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: raspOVOS-bookworm-arm64-lite-${{ env.current_date }}
          release_name: raspOVOS-bookworm-arm64-lite-${{ env.current_date }}
          body: |
            raspOVOS headless image
          draft: false
          prerelease: false
      -
        name: Upload to releases
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.create-image.outputs.image-path }}
          release_id: ${{ steps.create_release.outputs.id }}
          draft: false
          overwrite: true
          prerelease: false
          verbose: true
