name: Generate skill examples

on:
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install skills
        run: |
          pip install --pre ovos-plugin-manager
          pip install --pre -r skills.list

      - name: Generate skill examples per language
        run: |
          python docs/gen.py

      - name: Commit to dev
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update translations
          branch: dev
